<?php

Redux::setSection( $opt_name, array(
	'title'            => __( 'Header', 'themeplus-core' ),
	'id'               => 'header',
	'customizer_width' => '400px',
	'icon'             => 'el el-arrow-up',
) );

Redux::setSection( $opt_name, array(
	'title'         => __( 'Header', 'themeplus-core' ),
	'id'            => 'tp-header',
	'subsection'    => true,
	'fields'		=> 	array(
		array(
			'id'   	=> 'tp-section-header-type',
			'class'	=> 'tp-section-title',
			'type' => 'info',
			'desc' => __('Header Type', 'themeplus-core'),
		),
		array(
			'type'		=>	'button_set',
			'id'		=>	'tp-header-layout',
			'title'		=> 	__('Header Layout', 'themeplus-core' ),
			'subtitle'	=>	__('Select the type of header to display.', 'themeplus-core' ),
			'required' 	=> 	array('tp-top-header-show','equals','1'),
			'options'	=>	array(
				'header1'	=>	__('Header 1', 'themeplus-core' ),
				'header2'	=>	__('Header 2', 'themeplus-core' ),
			),
			'required' 	=> array('tp-top-header-show','equals','1'),
			'default' 	=> 'header1',
		),
	),
));

Redux::setSection( $opt_name, array(
	'title'         => __( 'Top Header', 'themeplus-core' ),
	'id'            => 'tp-top-header',
	'subsection'    => true,
	'fields'		=> 	array(
		array(
			'id'   	=> 'tp-section-top-header',
			'class'	=> 'tp-section-title',
			'type' => 'info',
			'desc' => __('Top Header', 'themeplus-core'),
		),
		array(
			'type'		=>	'switch',
			'id'		=>	'tp-top-header-show',
			'title'     => __( 'Show Top Header', 'themeplus-core' ),
			'subtitle'  => __( 'Check whether to show or hide the topbar.', 'themeplus-core' ),
			'on'		=> __('Show', 'themeplus-core'),
			'off'		=> __('Hide', 'themeplus-core'),
			'default'	=> true,
		),
		array(
			'type'					=>	'background',
			'id'					=>	'tp-top-header-background',
			'title'     			=> __( 'Background Color', 'themeplus-core' ),
			'subtitle'  			=> __( 'Controls the background color for the topbar.', 'themeplus-core' ),
			'background-repeat'     => false,
			'background-attachment' => false,
			'background-position'   => false,
			'background-image'      => false,
			'background-size'       => false,
			'preview'               => false,
			'transparent'			=> false,
			'class'					=> 'col-1of2',
			'required' 				=> array('tp-top-header-show','equals','1'),
			'output'				=> array('background-color'	=> '#tp-top-header-container'),
			'default'				=> array('background-color' => '#1e73be')
		),
		array(
			'id' 					=> 'tp-top-header-background-opacity',
			'type' 					=> 'slider',
			'title' 				=> __( 'Background Opacity' , 'themeplus-core' ),
			'subtitle' 				=> __( 'Select the transparency of the background for the top header' , 'themeplus-core' ),
			'step' 					=> 0.01,
			'resolution' 			=> 0.01,
			'float_mark'	 		=> '.',
			'class'					=> 'col-1of2',
			'required' 				=> array('tp-top-header-show','equals','1'),
			'default'				=> 1,
		),
		array(
			'id'       => 'tp-top-header-left',
			'type'     => 'select',
			'title'    => __('Top Header Left Content', 'themeplus-core'), 
			'subtitle' => __('Controls the content that displays in the top left section.', 'themeplus-core'),
			'options'  => array(
				'contact-info' 	=> 'Contact Info',
				'social-links' 	=> 'Social Links',
				'navigation' 	=> 'Navigation',
				'leave-empty' 	=> 'Leave Empty'
			),
			'default'  => 'contact-info',
		),
		array(
			'id'       => 'tp-top-header-right',
			'type'     => 'select',
			'title'    => __('Top Header Right Content', 'themeplus-core'), 
			'subtitle' => __('Controls the content that displays in the top right section.', 'themeplus-core'),
			'options'  => array(
				'contact-info' 	=> 'Contact Info',
				'social-links' 	=> 'Social Links',
				'navigation' 	=> 'Navigation',
				'leave-empty' 	=> 'Leave Empty'
			),
			'default'  => 'navigation',
		),
		array(
			'type'					=> 	'text',
			'id'					=>	'tp-top-header-email',
			'title'     			=> __( 'Email', 'themeplus-core' ),
			'subtitle'  			=> __( 'Link the email address in the topbar.', 'themeplus-core' ),
			'required' 				=> array('tp-top-header-show','equals','1'),
			'validate' 				=> 'email',
			'default'				=>	'email@yourwebsite.com',
		),
		array(
			'type'					=> 	'text',
			'id'					=>	'tp-top-header-phone',
			'title'     			=> __( 'Phone', 'themeplus-core' ),
			'subtitle'  			=> __( 'Enter the phone number in the topbar.', 'themeplus-core' ),
			'required' 				=> array('tp-top-header-show','equals','1'),
			'validate' 				=> 'no_html',
			'default'				=>	'+39 000 000 0000',
		),
		array(
			'type'					=>	'color',
			'id'					=>	'tp-top-header-color',
			'title'     			=> 	__( 'Text Color', 'themeplus-core' ),
			'subtitle'  			=> 	__( 'Set the text color in the topbar.', 'themeplus-core' ),
			'required' 				=> 	array('tp-top-header-show','equals','1'),
			'validate'				=>	'color',
			'transparent'			=>	false,
			'output'           		=> 	array('color'	=> '#tp-top-header, #tp-top-header a'),
			'default'				=>	'#ffffff',
		),
		array(
			'type'				=>	'spacing',
			'id'				=>	'tp-top-header-padding',
			'title'				=> 	__('Padding', 'themeplus-core' ),
			'subtitle'			=>	__('Select the padding you would apply for top header.', 'themeplus-core' ),
			'mode'				=>	'padding',
			'units'				=>	false,
			'units_extended'	=> 	true,
			'display_units'		=>	false,
			'required' 			=> 	array('tp-top-header-show','equals','1'),
			'output'         	=> 	array('#tp-top-header'),
		),
		array(
			'id' 					=> 'tp-top-header-menu-right-padding',
			'type' 					=> 'slider',
			'title' 				=> __( 'Top Header Menu Item Padding' , 'themeplus-core' ),
			'subtitle' 				=> __( 'Controls the right padding for top header menu text (left on RTL). In pixels.' , 'themeplus-core' ),
			'step' 					=> 1,
			'resolution' 			=> 1,
            'max'                   => 200,
			'float_mark'	 		=> '.',
			'default'				=> 20,
		),
	),
) );